/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const GalleryItem = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'createdAt' : Time,
  'blobId' : IDL.Text,
  'mediaType' : IDL.Variant({ 'video' : IDL.Null, 'photo' : IDL.Null }),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Event = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'comingSoon' : IDL.Null,
  }),
  'month' : IDL.Text,
  'marathonName' : IDL.Text,
  'city' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Text,
  'active' : IDL.Bool,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'quote' : IDL.Text,
  'rating' : IDL.Nat,
  'marathon' : IDL.Text,
});
export const Tour = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({ 'active' : IDL.Null, 'draft' : IDL.Null }),
  'title' : IDL.Text,
  'destination' : IDL.Text,
  'duration' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'inclusions' : IDL.Vec(IDL.Text),
  'highlights' : IDL.Vec(IDL.Text),
  'exclusions' : IDL.Vec(IDL.Text),
  'price' : IDL.Text,
  'itinerary' : IDL.Vec(
    IDL.Record({
      'day' : IDL.Nat,
      'title' : IDL.Text,
      'description' : IDL.Text,
    })
  ),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Inquiry = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'read' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'marathon' : IDL.Text,
});
export const Subscriber = IDL.Record({
  'subscribedAt' : Time,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGalleryItem' : IDL.Func([GalleryItem], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEvent' : IDL.Func([Event], [IDL.Text], []),
  'createTestimonial' : IDL.Func([Testimonial], [IDL.Text], []),
  'createTour' : IDL.Func([Tour], [IDL.Text], []),
  'deleteEvent' : IDL.Func([IDL.Text], [], []),
  'deleteTestimonial' : IDL.Func([IDL.Text], [], []),
  'deleteTour' : IDL.Func([IDL.Text], [], []),
  'getActiveTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getSubscribers' : IDL.Func([], [IDL.Vec(Subscriber)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getTour' : IDL.Func([IDL.Text], [Tour], ['query']),
  'getTours' : IDL.Func([], [IDL.Vec(Tour)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markInquiryRead' : IDL.Func([IDL.Text], [], []),
  'removeGalleryItem' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitInquiry' : IDL.Func([Inquiry], [IDL.Text], []),
  'subscribe' : IDL.Func([IDL.Text], [IDL.Text], []),
  'updateEvent' : IDL.Func([Event], [], []),
  'updateGalleryItem' : IDL.Func([GalleryItem], [], []),
  'updateTestimonial' : IDL.Func([Testimonial], [], []),
  'updateTour' : IDL.Func([Tour], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const GalleryItem = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'createdAt' : Time,
    'blobId' : IDL.Text,
    'mediaType' : IDL.Variant({ 'video' : IDL.Null, 'photo' : IDL.Null }),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Event = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'closed' : IDL.Null,
      'open' : IDL.Null,
      'comingSoon' : IDL.Null,
    }),
    'month' : IDL.Text,
    'marathonName' : IDL.Text,
    'city' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Text,
    'active' : IDL.Bool,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'quote' : IDL.Text,
    'rating' : IDL.Nat,
    'marathon' : IDL.Text,
  });
  const Tour = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({ 'active' : IDL.Null, 'draft' : IDL.Null }),
    'title' : IDL.Text,
    'destination' : IDL.Text,
    'duration' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'inclusions' : IDL.Vec(IDL.Text),
    'highlights' : IDL.Vec(IDL.Text),
    'exclusions' : IDL.Vec(IDL.Text),
    'price' : IDL.Text,
    'itinerary' : IDL.Vec(
      IDL.Record({
        'day' : IDL.Nat,
        'title' : IDL.Text,
        'description' : IDL.Text,
      })
    ),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Inquiry = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'read' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'marathon' : IDL.Text,
  });
  const Subscriber = IDL.Record({ 'subscribedAt' : Time, 'email' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGalleryItem' : IDL.Func([GalleryItem], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEvent' : IDL.Func([Event], [IDL.Text], []),
    'createTestimonial' : IDL.Func([Testimonial], [IDL.Text], []),
    'createTour' : IDL.Func([Tour], [IDL.Text], []),
    'deleteEvent' : IDL.Func([IDL.Text], [], []),
    'deleteTestimonial' : IDL.Func([IDL.Text], [], []),
    'deleteTour' : IDL.Func([IDL.Text], [], []),
    'getActiveTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getSubscribers' : IDL.Func([], [IDL.Vec(Subscriber)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getTour' : IDL.Func([IDL.Text], [Tour], ['query']),
    'getTours' : IDL.Func([], [IDL.Vec(Tour)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markInquiryRead' : IDL.Func([IDL.Text], [], []),
    'removeGalleryItem' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitInquiry' : IDL.Func([Inquiry], [IDL.Text], []),
    'subscribe' : IDL.Func([IDL.Text], [IDL.Text], []),
    'updateEvent' : IDL.Func([Event], [], []),
    'updateGalleryItem' : IDL.Func([GalleryItem], [], []),
    'updateTestimonial' : IDL.Func([Testimonial], [], []),
    'updateTour' : IDL.Func([Tour], [], []),
  });
};

export const init = ({ IDL }) => { return []; };