/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Event {
  'id' : string,
  'status' : { 'closed' : null } |
    { 'open' : null } |
    { 'comingSoon' : null },
  'month' : string,
  'marathonName' : string,
  'city' : string,
  'year' : bigint,
  'description' : string,
}
export interface GalleryItem {
  'id' : string,
  'title' : string,
  'order' : bigint,
  'createdAt' : Time,
  'blobId' : string,
  'mediaType' : { 'video' : null } |
    { 'photo' : null },
}
export interface Inquiry {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'read' : boolean,
  'email' : string,
  'message' : string,
  'phone' : string,
  'marathon' : string,
}
export interface Subscriber { 'subscribedAt' : Time, 'email' : string }
export interface Testimonial {
  'id' : string,
  'active' : boolean,
  'city' : string,
  'name' : string,
  'createdAt' : Time,
  'quote' : string,
  'rating' : bigint,
  'marathon' : string,
}
export type Time = bigint;
export interface Tour {
  'id' : string,
  'status' : { 'active' : null } |
    { 'draft' : null },
  'title' : string,
  'destination' : string,
  'duration' : string,
  'createdAt' : Time,
  'description' : string,
  'inclusions' : Array<string>,
  'highlights' : Array<string>,
  'exclusions' : Array<string>,
  'price' : string,
  'itinerary' : Array<
    { 'day' : bigint, 'title' : string, 'description' : string }
  >,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Gallery
   */
  'addGalleryItem' : ActorMethod<[GalleryItem], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Events
   */
  'createEvent' : ActorMethod<[Event], string>,
  /**
   * / Testimonials
   */
  'createTestimonial' : ActorMethod<[Testimonial], string>,
  /**
   * / Tours
   */
  'createTour' : ActorMethod<[Tour], string>,
  'deleteEvent' : ActorMethod<[string], undefined>,
  'deleteTestimonial' : ActorMethod<[string], undefined>,
  'deleteTour' : ActorMethod<[string], undefined>,
  'getActiveTestimonials' : ActorMethod<[], Array<Testimonial>>,
  /**
   * / User Profile Functions
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEvents' : ActorMethod<[], Array<Event>>,
  'getGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getSubscribers' : ActorMethod<[], Array<Subscriber>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getTour' : ActorMethod<[string], Tour>,
  'getTours' : ActorMethod<[], Array<Tour>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markInquiryRead' : ActorMethod<[string], undefined>,
  'removeGalleryItem' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Inquiries
   */
  'submitInquiry' : ActorMethod<[Inquiry], string>,
  /**
   * / Newsletter
   */
  'subscribe' : ActorMethod<[string], string>,
  'updateEvent' : ActorMethod<[Event], undefined>,
  'updateGalleryItem' : ActorMethod<[GalleryItem], undefined>,
  'updateTestimonial' : ActorMethod<[Testimonial], undefined>,
  'updateTour' : ActorMethod<[Tour], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];